import type { Post, Comment, Chat, Message } from '@/types'

export const MOCK_USER = {
  uid: 'mock-user-1',
  email: 'demo@meshimap.com',
  displayName: 'グルメ太郎',
  photoURL: 'https://i.pravatar.cc/150?img=11',
  bio: '食べることが大好き🍜 東京・大阪中心に美味しいものを探し中',
  followersCount: 128,
  followingCount: 64,
  postsCount: 12,
}

export const MOCK_POSTS: Post[] = [
  {
    id: 'post-1',
    userId: 'mock-user-1',
    userDisplayName: 'グルメ太郎',
    userPhotoURL: 'https://i.pravatar.cc/150?img=11',
    imageURLs: ['https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600'],
    caption: '渋谷の隠れ家ラーメン！スープが絶品でした🍜 #ラーメン #渋谷グルメ #東京',
    rating: 5,
    genre: 'ラーメン',
    priceRange: '¥1,001〜¥3,000',
    location: { name: '麺屋 天空 渋谷店', lat: 35.6595, lng: 139.7005 },
    hashtags: ['ラーメン', '渋谷グルメ', '東京'],
    likesCount: 42,
    commentsCount: 5,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'post-2',
    userId: 'mock-user-2',
    userDisplayName: 'さくら食堂',
    userPhotoURL: 'https://i.pravatar.cc/150?img=5',
    imageURLs: [
      'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=600',
      'https://images.unsplash.com/photo-1617196034183-421b4040ed20?w=600',
    ],
    caption: '新宿の老舗寿司屋さん✨ ネタが新鮮で大満足！また絶対来ます #寿司 #新宿 #和食',
    rating: 5,
    genre: '寿司',
    priceRange: '¥5,001〜¥10,000',
    location: { name: '寿司 銀座本店', lat: 35.6938, lng: 139.6982 },
    hashtags: ['寿司', '新宿', '和食'],
    likesCount: 87,
    commentsCount: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
  {
    id: 'post-3',
    userId: 'mock-user-3',
    userDisplayName: 'foodie_hana',
    userPhotoURL: 'https://i.pravatar.cc/150?img=20',
    imageURLs: ['https://images.unsplash.com/photo-1551024601-bec78aea704b?w=600'],
    caption: '代官山のおしゃれカフェ☕️ ケーキが可愛すぎて食べるのがもったいない #カフェ #スイーツ #代官山',
    rating: 4,
    genre: 'カフェ',
    priceRange: '¥1,001〜¥3,000',
    location: { name: 'Café Daikanyama', lat: 35.6488, lng: 139.7031 },
    hashtags: ['カフェ', 'スイーツ', '代官山'],
    likesCount: 134,
    commentsCount: 8,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    id: 'post-4',
    userId: 'mock-user-1',
    userDisplayName: 'グルメ太郎',
    userPhotoURL: 'https://i.pravatar.cc/150?img=11',
    imageURLs: ['https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600'],
    caption: '恵比寿の焼肉！和牛が口の中でとろける〜🥩 #焼肉 #和牛 #恵比寿',
    rating: 5,
    genre: '焼肉',
    priceRange: '¥5,001〜¥10,000',
    location: { name: '和牛焼肉 恵比寿', lat: 35.6466, lng: 139.7132 },
    hashtags: ['焼肉', '和牛', '恵比寿'],
    likesCount: 63,
    commentsCount: 4,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
  {
    id: 'post-5',
    userId: 'mock-user-4',
    userDisplayName: 'tanaka_eats',
    userPhotoURL: 'https://i.pravatar.cc/150?img=33',
    imageURLs: [
      'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600',
      'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600',
    ],
    caption: '銀座のフレンチレストラン✨ コースが最高でした。特にメインのお肉が絶品 #フレンチ #銀座 #記念日',
    rating: 5,
    genre: 'フレンチ',
    priceRange: '¥10,001〜',
    location: { name: 'Restaurant Ginza', lat: 35.6714, lng: 139.7653 },
    hashtags: ['フレンチ', '銀座', '記念日'],
    likesCount: 215,
    commentsCount: 21,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36),
  },
  {
    id: 'post-6',
    userId: 'mock-user-2',
    userDisplayName: 'さくら食堂',
    userPhotoURL: 'https://i.pravatar.cc/150?img=5',
    imageURLs: ['https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600'],
    caption: '浅草の老舗天ぷら屋🍤 サクサクで最高！観光ついでにぜひ #天ぷら #浅草 #和食',
    rating: 4,
    genre: '和食',
    priceRange: '¥3,001〜¥5,000',
    location: { name: '天ぷら 浅草', lat: 35.7148, lng: 139.7967 },
    hashtags: ['天ぷら', '浅草', '和食'],
    likesCount: 55,
    commentsCount: 3,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
  },
]

export const MOCK_COMMENTS: Comment[] = [
  {
    id: 'comment-1',
    postId: 'post-1',
    userId: 'mock-user-2',
    userDisplayName: 'さくら食堂',
    userPhotoURL: 'https://i.pravatar.cc/150?img=5',
    text: '私もここ行きました！スープ最高ですよね✨',
    createdAt: new Date(Date.now() - 1000 * 60 * 20),
  },
  {
    id: 'comment-2',
    postId: 'post-1',
    userId: 'mock-user-3',
    userDisplayName: 'foodie_hana',
    userPhotoURL: 'https://i.pravatar.cc/150?img=20',
    text: '気になってた！今度行ってみます🍜',
    createdAt: new Date(Date.now() - 1000 * 60 * 10),
  },
]

export const MOCK_CHATS: Chat[] = [
  {
    id: 'chat-1',
    participants: ['mock-user-1', 'mock-user-2'],
    participantDetails: {
      'mock-user-1': { displayName: 'グルメ太郎', photoURL: 'https://i.pravatar.cc/150?img=11' },
      'mock-user-2': { displayName: 'さくら食堂', photoURL: 'https://i.pravatar.cc/150?img=5' },
    },
    lastMessage: 'あのお店美味しかったですね！',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 45),
  },
  {
    id: 'chat-2',
    participants: ['mock-user-1', 'mock-user-3'],
    participantDetails: {
      'mock-user-1': { displayName: 'グルメ太郎', photoURL: 'https://i.pravatar.cc/150?img=11' },
      'mock-user-3': { displayName: 'foodie_hana', photoURL: 'https://i.pravatar.cc/150?img=20' },
    },
    lastMessage: '代官山のカフェ情報ありがとう😊',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 3),
  },
  {
    id: 'chat-3',
    participants: ['mock-user-1', 'mock-user-4'],
    participantDetails: {
      'mock-user-1': { displayName: 'グルメ太郎', photoURL: 'https://i.pravatar.cc/150?img=11' },
      'mock-user-4': { displayName: 'tanaka_eats', photoURL: 'https://i.pravatar.cc/150?img=33' },
    },
    lastMessage: '銀座のフレンチ予約しました！',
    lastMessageAt: new Date(Date.now() - 1000 * 60 * 60 * 24),
  },
]

export const MOCK_MESSAGES: Message[] = [
  {
    id: 'msg-1',
    chatId: 'chat-1',
    senderId: 'mock-user-2',
    senderDisplayName: 'さくら食堂',
    senderPhotoURL: 'https://i.pravatar.cc/150?img=5',
    text: '昨日の投稿見ましたよ！渋谷のラーメン美味しそうですね',
    createdAt: new Date(Date.now() - 1000 * 60 * 60),
  },
  {
    id: 'msg-2',
    chatId: 'chat-1',
    senderId: 'mock-user-1',
    senderDisplayName: 'グルメ太郎',
    senderPhotoURL: 'https://i.pravatar.cc/150?img=11',
    text: '最高でした！スープが濃くて深みがあって🍜',
    createdAt: new Date(Date.now() - 1000 * 60 * 55),
  },
  {
    id: 'msg-3',
    chatId: 'chat-1',
    senderId: 'mock-user-2',
    senderDisplayName: 'さくら食堂',
    senderPhotoURL: 'https://i.pravatar.cc/150?img=5',
    text: 'あのお店美味しかったですね！',
    createdAt: new Date(Date.now() - 1000 * 60 * 45),
  },
]
